#!/usr/bin/python3

import socket
import sys


s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#creates a socket object with address of IPV4 type and TCP socket.

Input= sys.argv[1]
a= Input.split(':')
IP= str(a[0])
port= int(a[1])
s.connect((IP, port))
print("Connected to :",Input)
print("The IP address of the server is:", IP)
print("The port number of the server is:", port)

firstmessage = s.recv(1024).decode() # to know what character set the string is encoded with.
print("\n", firstmessage) 
s.send("OK\n".encode())

while(True):
    message=s.recv(1024).decode()
    print(message)
    X=message.split()
    if len(X) > 1:

        if X[0] == "add":
            adds = int(X[1])+int(X[2])
            a1=str(adds)+"\n"
            s.send(a1.encode())
            print("result is ",str(adds) )

        elif X[0] == "sub":
            subs = int(X[1])-int(X[2])
            b1=str(subs)+"\n"
            s.send(b1.encode())
            print("result is ", str(subs ))
            
        elif X[0] == "mul":
            muls = int(X[1])*int(X[2])
            d1=str(muls)+"\n"
            s.send(d1.encode())
            print("result is ", str(muls))

        elif X[0] == "div":
            divs = int(X[1])/int(X[2])
            e1=str(divs)+"\n"
            s.send(e1.encode())
            print('result is %8.8g ', str(divs))

        elif X[0] == "fadd":
            floadd = float(X[1])+float(X[2])
            a1=str(floadd)+"\n"
            s.send(a1.encode())
            print('result is %8.8g ' %floadd)

        elif X[0] == "fsub":
            flosub = float(X[1])-float(X[2])
            b1=str(flosub )+"\n"
            s.send(b1.encode())
            print('result is %8.8g ' %flosub)

        elif X[0] == "fmul":
            flomul = float(X[1])*float(X[2])
            d1=str(flomul)+"\n"
            s.send(d1.encode())
            print('result is %8.8g' %flomul)

        elif X[0] == "fdiv":
            flodiv = float(X[1])/float(X[2])
            e1=str(flodiv)+"\n"
            s.send(e1.encode())
            print('result is %8.8g' %flodiv)

        response = s.recv(1024).decode()
        print(response)
    break


s.close
