#!/usr/bin/python3

import socket		 	            
import sys
import random

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

Input = sys.argv[1]
split = Input.split(':')
IP = str(split[0])
port = int(split[1])
s.bind((IP, port))
print("Server is active")

#operations to perform are taken random for each input that is taken.

Operations = ["add", "sub", "mul", "div", "fadd", "fsub", "fmul", "fdiv"]

while True:
	c, addr = s.accept()
	print("Connected to :",Input)
	c.send("TEXT TCP 1.0\n".encode())
	Message = c.recv(1024).decode()
	print(Message)

	while True:
		operator = random.choice (Operations)
		if operator == "add":
			a = random.randint(1,2000) #given random numbers from 1 to 2000
			b = random.randint(1,3000) #given random numbers from 1 to 3000
			Toperform = operator + " " + str(a) + " " + str(b)
			addition = a + b
			c.send(Toperform.encode())
			result=c.recv(1024).decode()
			print ("result is", addition)
			if addition == int(result):
				c.send("success\n".encode())
			else:
				c.send("failure\n".encode())

		elif operator == "sub":
			a = random.randint(1,2000)#given random numbers from 1 to 2000
			b = random.randint(1,3000)#given random numbers from 1 to 3000
			Toperform = operator + " " + str(a) + " " + str(b)
			subtraction = a - b
			c.send(Toperform.encode())
			result=c.recv(1024).decode()
			print ("result is", subtraction)
			if subtraction == int(result):
				c.send("success\n".encode())
				
			else:
				c.send("failure\n".encode())

		elif operator == "mul":
			a = random.randint(1,2000) #given random numebers from 1 to 2000
			b = random.randint(1,3000) #given random numbers from 1 to 3000
			Toperform = operator + " " + str(a) + " " + str(b)
			multiplication = a * b
			print ("result is", multiplication)
			c.send(Toperform.encode())
			result=c.recv(1024).decode()
			if multiplication == int(result):
				c.send("success\n".encode())
				
			else:
				c.send("failure\n".encode())

		elif operator == "div":
			a = random.randint(1,2000) #given random numebers from 1 to 2000
			b = random.randint(1,3000) #given random numbers from 1 to 3000
			Toperform = operator + " " + str(a) + " " + str(b)
			division = a / b
			c.send(Toperform.encode())
			result=c.recv(1024).decode()
			print ('result is ' %division)
			if division == float(result):
				c.send("success\n".encode())
				
			else:
				c.send("failure\n".encode())

		elif operator == "fadd":
			a = random.uniform(1,2000) #given random numebers from 1 to 2000
			b = random.uniform(1,3000) #given random numbers from 1 to 3000
			Toperform = operator + " " + str(a) + " " + str(b)
			faddition = a + b
			c.send(Toperform.encode())
			result=c.recv(1024).decode()
			print ('result is ' %faddition)
			if faddition == float(result):
				c.send("success\n".encode())
				
			else:
				c.send("failure\n".encode())

		elif operator == "fsub":
			a = random.uniform(1,2000)#given random numebers from 1 to 2000
			b = random.uniform(1,3000)#given random numbers from 1 to 3000
			Toperform = operator + " " + str(a) + " " + str(b)
			fsubtraction = a - b
			c.send(Toperform.encode())
			result=c.recv(1024).decode()
			print ('result is ' %fsubtraction)
			if fsubtraction == float(result):
				c.send("success\n".encode())
				
			else:
				c.send("failure\n".encode())

		elif operator == "fmul":
			a = random.uniform(1,2000)#given random numebers from 1 to 2000
			b = random.uniform(1,3000)#given random numbers from 1 to 3000
			Toperform = operator + " " + str(a) + " " + str(b)
			fmultiplication = a * b
			c.send(Toperform.encode())
			result=c.recv(1024).decode()
			print ('result is ' %fmultiplication)
			if fmultiplication == float(result):
				c.send("success\n".encode())
				
			else:
				c.send("failure\n".encode())

		elif operator == "fdiv":
			a = random.uniform(1,2000)#given random numebers from 1 to 2000
			b = random.uniform(1,3000)#given random numbers from 1 to 3000
			Toperform = operator + " " + str(a) + " " + str(b)
			fdivision = a / b
			c.send(Toperform.encode())
			result=c.recv(1024).decode()
			print ('result is ' %fdivision)
			
			if fdivision == float(result):
				c.send("success\n".encode())
			
			else:
				c.send("failure\n".encode())


			
		else:
    			print("Invalid input Please give the correct information")
		break


c.close() #close the connection
